name: Deploy python greetings app

inputs:
  env_name:
    required: true
  port:
    required: true
  app_path:
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v6

    - uses: actions/checkout@v6
      with:
        repository: mtararujs/python-greetings
        path: ${{ inputs.app_path }}

    - run: |
        if exist C:\greetings-apps\greetings-app-${{ inputs.env_name }} rmdir /s /q C:\greetings-apps\greetings-app-${{ inputs.env_name }}
        if not exist C:\greetings-apps mkdir C:\greetings-apps
        xcopy /E /I /Y ${{ inputs.app_path }} C:\greetings-apps\greetings-app-${{ inputs.env_name }}\
      shell: cmd

    - run: python -m venv venv
      shell: cmd
      working-directory: C:\greetings-apps\greetings-app-${{ inputs.env_name }}

    - run: venv\Scripts\python.exe -m pip install -r requirements.txt
      shell: cmd
      working-directory: C:\greetings-apps\greetings-app-${{ inputs.env_name }}

    - run: pm2 delete greetings-app-${{ inputs.env_name }} & set "errorlevel=0"
      shell: cmd
      working-directory: C:\greetings-apps\greetings-app-${{ inputs.env_name }}

    - run: set RUNNER_TRACKING_ID= & pm2 start app.py --name greetings-app-${{ inputs.env_name }} --interpreter venv\Scripts\python.exe -- --port ${{ inputs.port }}
      shell: cmd
      working-directory: C:\greetings-apps\greetings-app-${{ inputs.env_name }}

    - run: powershell -Command "Start-Sleep -Seconds 5"
      shell: cmd
      working-directory: C:\greetings-apps\greetings-app-${{ inputs.env_name }}
