name: Deploy python greetings app

inputs:
  env_name:
    required: true
  port:
    required: true
  app_path:
    required: true

runs:
  using: composite
  steps:
    - name: Checkout pipeline repo
      uses: actions/checkout@v6

    - name: Clone python-greetings
      uses: actions/checkout@v6
      with:
        repository: mtararujs/python-greetings
        path: ${{ inputs.app_path }}

    - name: Create venv
      run: python -m venv venv
      shell: cmd
      working-directory: ${{ inputs.app_path }}

    - name: Install requirements
      run: venv\Scripts\python.exe -m pip install -r requirements.txt
      shell: cmd
      working-directory: ${{ inputs.app_path }}

    - name: Delete old PM2 process
      run: pm2 delete greetings-app-${{ inputs.env_name }} & set "errorlevel=0"
      shell: cmd
      working-directory: ${{ inputs.app_path }}

    - name: Start app with PM2
      run: pm2 start app.py --name greetings-app-${{ inputs.env_name }} --interpreter venv\Scripts\python.exe -- --port ${{ inputs.port }}
      shell: cmd
      working-directory: ${{ inputs.app_path }}
