name: Python Greetings Pipeline

on:
  workflow_dispatch:

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v6

      - name: Debug files
        run: type .github\actions\install-pip-deps\action.yml
        shell: cmd

      - name: Install Python dependencies
        uses: ./.github/actions/install-pip-deps
        with:
          app_path: python-greetings
