jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v6

      - name: Install Python dependencies
        uses: ./.github/actions/install-pip-deps
        with:
          app_path: python-greetings

  deploy-to-dev:
    runs-on: self-hosted
    needs: install-pip-deps
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v6

      - name: Deploy to DEV
        uses: ./.github/actions/deploy
        with:
          env_name: dev
          port: "7001"
          app_path: python-greetings

  tests-on-dev:
    runs-on: self-hosted
    needs: deploy-to-dev
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v6

      - name: Run tests on DEV
        uses: ./.github/actions/test
        with:
          env_name: dev
          test_path: course-js-api-framework
